### PR TITLE
65 eslint setup pre push hook for testinglinting

### PR DESCRIPTION
**Pull request by perennialAutodidact**
﻿## Description of changes 
- Installed `husky` and set up Git hooks
  - `pre-commit` - runs `yarn lint --fix` for each package, fixing linting errors and adding them to the commit before it's committed
  - `pre-push` - runs `yarn ci` for each package and will prevent pushing if any tests are failing. This can be prevented by passing the `--no-verify` flag when pushing changes. `git push --no-verify`.

## Test steps

- Run `yarn install` in the root directory

### `pre-commit`
- Open `backend/app.js` and change one of the imports to use double quotes.
- Save the file with the linting errors that appear. Hit `Ctrl + Shift + P` and enter "Save without formatting" if format-on-save is enabled
- Open `frontend/App.jsx` and change one of the imports to use double quotes.
- Save the file with linting errors.
- Open `frontend/styles/index.scss` and add `$test: .1;`. Save without formatting. There's a style linting rule that requires leading zeros on floating point values
- Run `git add -A` and `git commit -m "pre-commit linting test"`
- The `pre-commit` git hook should run and change the double quotes back to single quotes and adds a leading zero before making the commit

### `pre-push`
- Break a single front end test somehow
- Commit the changes
- Run `git push` to attempt to push the branch
- The test suites should run and the push should be prevented due to the broken test
- Fix the test, commit, push
- Once all tests are passing, the branch should push successfully

### CODE REVIEW

**Comment by russfraze** [comment]
I followed the test steps and it in the terminal it looks like it changed the files from the feedback but it didn't actually change the code in the files. The double quotes are still there, etc. 
Screen Shot 2023-11-01 at 1 13 26 PM

**Comment by perennialAutodidact** [comment]
Everything works on my end, so I'd need know more to help.

**Comment by perennialAutodidact** [comment]
- Check Node version
- Check if there are any unpulled changes
- Delete `node_modules` and run `yarn install` in the front and back end packages?

**Review by russfraze — APPROVED** [review]
Tested and working on my end.

**Pull request merged**
