### PR TITLE
69 add consolelog to eslint rules

### PR DESCRIPTION
**Pull request by perennialAutodidact**
﻿## Description of changes
- Added `no-console` rule to ESLint config, disallowing `console.log`, but allowing `console.warn` and `console.error` in the back end package and `console.warn` in the front end package

## Test steps
- (Re)Start both the front and back end servers
- In `backend/app.js`, add a `console.log`, `console.warn`, and `console.error`
- Verify that the warn and error statements are allowed, but the log statement shows as an error
- In `frontend/app.jsx`, add a `console.log`, `console.warn` and `console.error`.
- Verify that the warn statement is allowed, but the others are marked as linting errors

### CODE REVIEW

**Comment by russfraze** [comment]
This one again is working for me on the frontend but not the backend. 
Screen Shot 2023-11-01 at 1 44 45 PM
This isn't giving me linting errors.

**Comment by perennialAutodidact** [comment]
`console.warn` and `console.error` are both allowed in the backend repo. The frontend repo only allows `console.warn`

**Comment by perennialAutodidact** [comment]
Try hitting Cmd + Shift + P and entering Developer: Restart Extension Host and see if it makes the warnings appear. This fixed it for me.

**Comment by russfraze** [comment]
It looks like this branch has conflicts with dev.

**Review by russfraze — APPROVED** [review]

**Pull request merged**
